/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package internationalization;

import java.text.DateFormat;
import java.text.NumberFormat;
import java.util.Date;
import java.util.Locale;
import java.util.ResourceBundle;

/**
 *
 * @author mca237
 */
public class Form extends javax.swing.JFrame {

    /**
     * Creates new form local
     */
    public Form() {
        initComponents();
        jcbcountry.setSelectedIndex(0);
        jrbtranlate.setActionCommand("translate");
        jrbdatetime.setActionCommand("date-time");
        jrbnumber.setActionCommand("number");
        jrbcurrency.setActionCommand("currency");
        jrbtranlate.setSelected(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jtab = new javax.swing.JTabbedPane();
        jtablocal = new javax.swing.JPanel();
        jcbcountry = new javax.swing.JComboBox();
        jlbldisplay = new javax.swing.JLabel();
        jtabformats = new javax.swing.JPanel();
        jtxtinput = new javax.swing.JTextField();
        jrbtranlate = new javax.swing.JRadioButton();
        jrbdatetime = new javax.swing.JRadioButton();
        jcbformat = new javax.swing.JComboBox();
        jbtnsubmit = new javax.swing.JButton();
        jrbcurrency = new javax.swing.JRadioButton();
        jrbnumber = new javax.swing.JRadioButton();
        jlblformat = new javax.swing.JLabel();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jtab.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jcbcountry.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "U.S.A", "India", "France", "Spain" }));
        jcbcountry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbcountryActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jtablocalLayout = new javax.swing.GroupLayout(jtablocal);
        jtablocal.setLayout(jtablocalLayout);
        jtablocalLayout.setHorizontalGroup(
            jtablocalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jtablocalLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jtablocalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlbldisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbcountry, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(76, Short.MAX_VALUE))
        );
        jtablocalLayout.setVerticalGroup(
            jtablocalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jtablocalLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jcbcountry, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80)
                .addComponent(jlbldisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jtab.addTab("Locale", jtablocal);

        jtabformats.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        buttonGroup1.add(jrbtranlate);
        jrbtranlate.setText("Translate");

        buttonGroup1.add(jrbdatetime);
        jrbdatetime.setText("Date Time");

        jcbformat.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "UK", "USA", "France", "Germany" }));

        jbtnsubmit.setText("Submit");
        jbtnsubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnsubmitActionPerformed(evt);
            }
        });

        buttonGroup1.add(jrbcurrency);
        jrbcurrency.setText("Currency");

        buttonGroup1.add(jrbnumber);
        jrbnumber.setText("Number");

        jlblformat.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout jtabformatsLayout = new javax.swing.GroupLayout(jtabformats);
        jtabformats.setLayout(jtabformatsLayout);
        jtabformatsLayout.setHorizontalGroup(
            jtabformatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jtabformatsLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jtxtinput, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jcbformat, 0, 84, Short.MAX_VALUE)
                .addGap(37, 37, 37))
            .addGroup(jtabformatsLayout.createSequentialGroup()
                .addGroup(jtabformatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jtabformatsLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jrbtranlate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jtabformatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jtabformatsLayout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jbtnsubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jtabformatsLayout.createSequentialGroup()
                                .addComponent(jrbdatetime)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jrbnumber)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jrbcurrency))))
                    .addGroup(jtabformatsLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jlblformat, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jtabformatsLayout.setVerticalGroup(
            jtabformatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jtabformatsLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jtabformatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtxtinput)
                    .addComponent(jcbformat))
                .addGap(18, 18, 18)
                .addGroup(jtabformatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrbtranlate)
                    .addComponent(jrbdatetime)
                    .addComponent(jrbnumber)
                    .addComponent(jrbcurrency))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtnsubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlblformat, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        jtab.addTab("Formats", jtabformats);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jtab, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jtab)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcbcountryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbcountryActionPerformed
        // TODO add your handling code here:
        System.out.println(jcbcountry.getSelectedIndex());
        
        Locale local;
        switch (jcbcountry.getSelectedIndex()){
            case 1:
                local = new Locale("hi","IN");
                break;
            case 2:
                local = new Locale("fr","FR");
                break;
            case 3:
                local = new Locale("es","ES");
                break;
            default:
                local = new Locale("en","US");
                break;
        }
        String message ="<HTML> Country : " + local.getDisplayCountry();
        message +="<br>Language : " + local.getDisplayLanguage();
        message +="<br>Name : "+ local.getDisplayName();
        message +="<br>Country Code : "+ local.getISO3Country();
        message +="<br>Language Code : "+ local.getISO3Language() + "</html>";
        jlbldisplay.setText(message);
    }//GEN-LAST:event_jcbcountryActionPerformed

    private void jbtnsubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnsubmitActionPerformed
        // TODO add your handling code here:
        int countryindex = jcbformat.getSelectedIndex();
        String actionname = buttonGroup1.getSelection().getActionCommand();
        Locale l[] ={Locale.UK,Locale.US,Locale.FRANCE,Locale.GERMANY};
        Locale local = l[countryindex];
        switch(actionname){
            case "translate":
                Locale.setDefault(local);
                ResourceBundle bundle = ResourceBundle.getBundle("MessageBundle");
                jlblformat.setText(bundle.getString(jtxtinput.getText()));
                
                break;
            case "date-time":
               // DateFormat d1 = DateFormat.getDateInstance(DateFormat.DEFAULT, local);
               // DateFormat d2 = DateFormat.getTimeInstance(DateFormat.DEFAULT, local);
                DateFormat d3 = DateFormat.getDateTimeInstance(DateFormat.DEFAULT,DateFormat.DEFAULT, local);
                Date d = new Date();
                jlblformat.setText(d3.format(d));
                break;
            case "number":
                NumberFormat n = NumberFormat.getInstance(local);
                double number = Double.parseDouble(jtxtinput.getText());
                jlblformat.setText(n.format(number));
                break;
            case "currency":
                 NumberFormat c = NumberFormat.getCurrencyInstance(local);
                double currency = Double.parseDouble(jtxtinput.getText());
                jlblformat.setText(c.format(currency));
                break;       
            default:
                jlblformat.setText("NAA");
        }
    }//GEN-LAST:event_jbtnsubmitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JButton jbtnsubmit;
    private javax.swing.JComboBox jcbcountry;
    private javax.swing.JComboBox jcbformat;
    private javax.swing.JLabel jlbldisplay;
    private javax.swing.JLabel jlblformat;
    private javax.swing.JRadioButton jrbcurrency;
    private javax.swing.JRadioButton jrbdatetime;
    private javax.swing.JRadioButton jrbnumber;
    private javax.swing.JRadioButton jrbtranlate;
    private javax.swing.JTabbedPane jtab;
    private javax.swing.JPanel jtabformats;
    private javax.swing.JPanel jtablocal;
    private javax.swing.JTextField jtxtinput;
    // End of variables declaration//GEN-END:variables
}
