/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package localization;

import java.util.Locale;

/**
 *
 * @author mca237
 */
public class local extends javax.swing.JFrame {

    /**
     * Creates new form local
     */
    public local() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtab = new javax.swing.JTabbedPane();
        jtablocal = new javax.swing.JPanel();
        jcbcountry = new javax.swing.JComboBox();
        jlbldisplay = new javax.swing.JLabel();
        jtabformats = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jtab.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jcbcountry.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "U.S.A", "India", "France", "Spain" }));
        jcbcountry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbcountryActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jtablocalLayout = new javax.swing.GroupLayout(jtablocal);
        jtablocal.setLayout(jtablocalLayout);
        jtablocalLayout.setHorizontalGroup(
            jtablocalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jtablocalLayout.createSequentialGroup()
                .addGroup(jtablocalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jtablocalLayout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jlbldisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jtablocalLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jcbcountry, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(81, Short.MAX_VALUE))
        );
        jtablocalLayout.setVerticalGroup(
            jtablocalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jtablocalLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jcbcountry, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlbldisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(78, Short.MAX_VALUE))
        );

        jtab.addTab("Locale", jtablocal);

        javax.swing.GroupLayout jtabformatsLayout = new javax.swing.GroupLayout(jtabformats);
        jtabformats.setLayout(jtabformatsLayout);
        jtabformatsLayout.setHorizontalGroup(
            jtabformatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 313, Short.MAX_VALUE)
        );
        jtabformatsLayout.setVerticalGroup(
            jtabformatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 227, Short.MAX_VALUE)
        );

        jtab.addTab("Formats", jtabformats);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jtab, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jtab)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcbcountryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbcountryActionPerformed
        // TODO add your handling code here:
        System.out.println(jcbcountry.getSelectedIndex());
        
        Locale local;
        switch (jcbcountry.getSelectedIndex()){
            case 1:
                local = new Locale("hi","IN");
                break;
            case 2:
                local = new Locale("fr","FR");
                break;
            case 3:
                local = new Locale("es","ES");
                break;
            default:
                local = new Locale("en","US");
                break;
        }
        String message ="<HTML> Country : " + local.getDisplayCountry();
        message +="<br>Language : " + local.getDisplayLanguage();
        message +="<br>Name : "+ local.getDisplayName();
        message +="<br>Country Code : "+ local.getISO3Country();
        message +="<br>Language Code : "+ local.getISO3Language() + "</html>";
        jlbldisplay.setText(message);
    }//GEN-LAST:event_jcbcountryActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(local.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(local.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(local.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(local.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new local().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jcbcountry;
    private javax.swing.JLabel jlbldisplay;
    private javax.swing.JTabbedPane jtab;
    private javax.swing.JPanel jtabformats;
    private javax.swing.JPanel jtablocal;
    // End of variables declaration//GEN-END:variables
}
